### ISSUE TITLE
ISE 500 for non-existent entities

### ISSUE THREAD

**Issue by osvetlik** [cagysek/accountingApp#1]
This is a blocker issue and must be fixed. When I manually modify a detail URL, I get ISE 500 instead of 404 Not Found.
```
http://172.30.0.84/invoice-detail?invoice-id=355
```
![cagysek-ise500](https://user-images.githubusercontent.com/16480390/71787409-a6db6a80-3017-11ea-8010-015d5b5d93a4.png)

**Comment by cagysek** [comment]
Added condition for check database result before counting invoice prices
